name: Die Glorreichen
title: Die Glorreichen
description: Einmal glorreich, immer glorreich!

host: 0.0.0.0
port: 3000
permalink: /:title/
paginate: 10
highlighter: pygments
url: 'http://glorrei.ch'
baseurl: ''
exclude: ['README.md']
