# Site settings
title: Die Glorreichen
email: poisoned@glorrei.ch
description: > # this means to ignore newlines until "baseurl:"
  Hier ensteht die Webpräsenz von den Glorreichen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://glorrei.ch" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
