name: Die Glorreichen
title: Die Glorreichen
description: Einmal glorreich, immer glorreich!

host: 0.0.0.0
port: 3000
permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md']
